// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: image.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
  image_name,
  image_data
) VALUES (
  $1, $2
) RETURNING id, image_name, image_data
`

type CreateImageParams struct {
	ImageName string `json:"image_name"`
	ImageData []byte `json:"image_data"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.ImageName, arg.ImageData)
	var i Image
	err := row.Scan(&i.ID, &i.ImageName, &i.ImageData)
	return i, err
}
