// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Category struct {
	ID           int64  `json:"id"`
	CategoryName string `json:"category_name"`
}

type Image struct {
	ID        int64  `json:"id"`
	ImageName string `json:"image_name"`
	ImageData []byte `json:"image_data"`
}

type Post struct {
	ID           int64     `json:"id"`
	PostImage    int64     `json:"post_image"`
	Title        string    `json:"title"`
	PostCategory int64     `json:"post_category"`
	Content      string    `json:"content"`
	TimeForRead  int32     `json:"time_for_read"`
	CreatedAt    time.Time `json:"created_at"`
}

type Product struct {
	ID              int64   `json:"id"`
	ProductImage    int64   `json:"product_image"`
	ProductName     string  `json:"product_name"`
	ProductCategory int64   `json:"product_category"`
	SoldNumber      int32   `json:"sold_number"`
	Brand           string  `json:"brand"`
	Color           string  `json:"color"`
	ScreenSize      string  `json:"screen_size"`
	HardDiskSize    string  `json:"hard_disk_size"`
	Display         string  `json:"display"`
	Graphic         string  `json:"graphic"`
	Processor       string  `json:"processor"`
	InTheBox        string  `json:"in_the_box"`
	Height          string  `json:"height"`
	Width           string  `json:"width"`
	Cost            int64   `json:"cost"`
	Star            float64 `json:"star"`
}
