// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID           int64  `json:"id"`
	CategoryName string `json:"category_name"`
}

type Image struct {
	ID        int64  `json:"id"`
	ImageName string `json:"image_name"`
	ImageData []byte `json:"image_data"`
}

type Post struct {
	ID           int64     `json:"id"`
	PostImage    int64     `json:"post_image"`
	Title        string    `json:"title"`
	PostCategory int64     `json:"post_category"`
	Content      string    `json:"content"`
	TimeForRead  int32     `json:"time_for_read"`
	CreatedAt    time.Time `json:"created_at"`
}

type Product struct {
	ID              int64          `json:"id"`
	ProductImage    int64          `json:"product_image"`
	ProductName     string         `json:"product_name"`
	ProductCategory int64          `json:"product_category"`
	SoldNumber      sql.NullInt32  `json:"sold_number"`
	Brand           sql.NullString `json:"brand"`
	Color           sql.NullString `json:"color"`
	ScreenSize      sql.NullString `json:"screen_size"`
	HardDiskSize    sql.NullString `json:"hard_disk_size"`
	Display         sql.NullString `json:"display"`
	Graphic         sql.NullString `json:"graphic"`
	Processor       sql.NullString `json:"processor"`
	InTheBox        sql.NullString `json:"in_the_box"`
	Height          sql.NullString `json:"height"`
	Width           sql.NullString `json:"width"`
	Cost            int64          `json:"cost"`
	Star            float64        `json:"star"`
}
