import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import path from "path";
import { CssBaseline, ThemeProvider, createTheme } from "@mui/material";
import Theme from "@/theme/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <Theme>
        <body className={inter.className}>{children}</body>
      </Theme>
    </html>
  );
}
